DROP TABLE IF EXISTS user_tab;
CREATE TABLE user_tab (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (username),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS item_tab;
CREATE TABLE item_tab (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    category_id INT NOT NULL,
    description TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (name, category_id),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS review_tab;
CREATE TABLE review_tab (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    description TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX(user_id),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS item_image_tab;
CREATE TABLE item_image_tab (
    id INT NOT NULL AUTO_INCREMENT,
    item_id INT NOT NULL,
    image_link TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX(item_id),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS category_tab;
CREATE TABLE category_tab (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX(name),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS rating_tab;
CREATE TABLE rating_tab (
    id INT NOT NULL AUTO_INCREMENT,
    reviewer_id INT NOT NULL,
    reviewee_id INT NOT NULL,
    rating INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX(reviewee_id),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS offer_tab;
CREATE TABLE offer_tab (
    id INT NOT NULL AUTO_INCREMENT,
    buyer_id INT NOT NULL,
    seller_id INT NOT NULL,
    item_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS notification_tab;
CREATE TABLE notification_tab (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    description TEXT NOT NULL,
    read_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
